[features]
seeds = false
skip-lint = false
[programs.localnet]
counterapp = "DXs6ceVoR4hKbcE15C5g1AmjdAuU7d14ZjNP8eUxMR11"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/billyzhang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
